### PR TITLE
set default extreme_filter se to box

### LINKED ISSUE #68: incorrect `extremefilt!` implementation
```julia
julia> M = [4 6 5 3 4; 8 6 9 4 8; 7 8 4 9 6; 6 2 2 1 7; 1 6 5 2 6]
5×5 Matrix{Int}:
 4  6  5  3  4
 8  6  9  4  8
 7  8  4  9  6
 6  2  2  1  7
 1  6  5  2  6
```

I would expect the result should not be affected by its filtering order:

```julia
julia> using ImageMorphology: extremefilt!

julia> out = extremefilt!(copy(M), min)
 4  4  3  3  3
 4  4  3  3  3
 2  2  1  1  1
 1  1  1  1  1
 1  1  1  1  1
```

Notice that `M[3, 1]` doesn't contain `2` in its C4 neighborhood thus the "correct" value of `out[3,1]` should be `6`.

The solution is simple: extending `extremefilt!(f, A)` to `extremefilt!(f, out, A)` so that the original image source is unmodified.

For backward compatibility, we can still provide the `extremefilt!(f, out, A=out)` version but with clear documentation that the result depends on filtering order and may vary from time to time.

cc: @timholy as you seem to be the original author of this function

### PR DESCRIPTION
**Pull request by johnnychen94**
This changes the default se for the new `extreme_filter` to be box shape, i.e., C8 for 2d, C27 for 3d. This is consistent with the previous `extremefilt!` implementation.

fixes #68

This will be a breaking change, so the next release ImageMorphology will be 0.4.0.

cc: @ThomasRetornaz

### CODE REVIEW

**Review by ThomasRetornaz — APPROVED** [review]
Looks good to me

File: src/extreme_filter.jl [hunk 1]
```diff
@@ -49,9 +49,9 @@ julia> extreme_filter(max, M; dims=(1, )) # max-filter along the first dimension
 connectivity, or a `AbstractArray{<:CartesianIndex}` array with each element indicating the
 displacement offset to its center element.
 
-```
-julia> Ω_mask = Bool[1 1 0; 1 1 0; 1 0 0] # custom neighborhood in mask format
-3×3 Matrix{Bool}:
+```jldoctest extreme_filter
+julia> Ω_mask = centered(Bool[1 1 0; 1 1 0; 1 0 0]) # custom neighborhood in mask format
+3×3 OffsetArray(::Matrix{Bool}, -1:1, -1:1) with eltype Bool with indices -1:1×-1:1:
  1  1  0
```
Comment (ThomasRetornaz) [inline src/extreme_filter.jl:55]: Warning! be aware that in case of non symmetrical SE, the SE should be transposed before exteme_filter call
Its the difference between erode/dilate and minkowski -,+
see https://people.cmm.minesparis.psl.eu/users/serra/cours/pdf/en/ch2en.pdf p7 or soille book
Anyway transpose is ship so may we could always run that transform instead of detect non symmetric property first

**Review by ThomasRetornaz — APPROVED** [review]
My only concern is on non symmetrical SE.
See my comment above

File: src/extreme_filter.jl (hunk 1 above)
Comment (johnnychen94) [reply src/extreme_filter.jl:55]: I see; this seems to be a comment on the conceptual confusion, that is, dilation is a Minkowski addition iff the SE is symmetric with respect to its origin.

This can be part of the documentation, but for `extreme_filter`, and `dilate`, `erode`. I believe we don't need to change it.
